[tox]
envlist = py314

[testenv]
deps =
    pytest
    python-dotenv
    pyodbc
    fastapi
    uvicorn
    sqlalchemy
    pydantic
    jinja2
    python-multipart
    pandas
    vaderSentiment
    httpx
commands = pytest

[testenv:flake8]
deps =
    flake8
    flake8-bugbear
    flake8-docstrings
    flake8-typing-imports
    pep8-naming
exclude =
    __pycache__
    setup.py
    venv/**/.*
commands =
    flake8 --ignore=B001,B036,E501,E402 src tests